### ISSUE TITLE
[meta issue] make all Nim APIs generic: ctor, init, to, streams, types, etc

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#41]
All these will simplify some API's by making them generic with less duplication:

- [ ] constructors: https://github.com/nim-lang/Nim/issues/7474 newFoo[T](args) => Foo.New[T](args)
- [ ] initializers: (TODO: file issue) initFoo[T](args) => Foo.Init[T](args)
- [ ] converters/parsers: https://github.com/nim-lang/Nim/issues/7430 a.parseBool => a.to[bool] or a.parse[bool]
- [ ] streams: https://github.com/nim-lang/Nim/pull/7481 readBool => read[bool]
- [ ] macros.nim: nnkInt32Lit => nnkLit[int32] (eg will simplify `newLit`, etc)
- [ ] typeinfo.nim: getUInt32  => getType[uint32]
- [ ] json: newJBool => newJType[bool], getBool => getType[bool]

## NOTE about `generic` meaning
Nim generics can be overloaded (eg: `proc foo[T:int|bool]()` or even with `proc foo[T:isConceptBar]()` unlike java generics, so the term can be confusing for some and indeed it tripped a few people recently (eg https://github.com/nim-lang/Nim/issues/7430#issuecomment-377473190 , https://github.com/nim-lang/Nim/issues/3502#issuecomment-378292623 ), maybe Nim docs could clarify this aspect. The point is we want to have generic (in Nim's sense of overloadable generics) APIs as much as possible, as legacy API's like `parseBool` make generic code hard to use (API writer needs special case for each type eg bool), reminiscent of C and go.

## tell-tell sign that generic api's are needed:
lots of very similar code blocks repeated for several distinct types

eg: in macros.nim:
```
proc newLit*(i: int32): NimNode {.compileTime.} =
  ## produces a new integer literal node.
  result = newNimNode(nnkInt32Lit)
  result.intVal = i

proc newLit*(i: int64): NimNode {.compileTime.} =
  ## produces a new integer literal node.
  result = newNimNode(nnkInt64Lit)
  result.intVal = i
# etc (lots of overloads)
```

could become simply:
```
proc newLit*[T](i: T): NimNode {.compileTime.} =
  result = NimNode.New(nnkLit[T])
  result.val[T] = i
```

## motivation
non-generic API's (eg json newJBool) is viral: it causes calling functions to also be non-generic, or pushes the complexity on them to wrap them into a generic API

## how to rewrite API's (typedesc vs generics) ?
https://github.com/nim-lang/Nim/issues/7517 [RFC] guidelines for when to use typedesc vs generics

**Comment by PMunch** [comment]
I'd really like to see this be adopted to the entire stdlib for Nim v2. It makes it easier to write macros and generics, and it looks much cleaner. The last part is quite subjective of course but I find `var x = "100".parse(int)` much nicer than `var x = "100".parseInt()`, same goes for `var x = new MyType` vs `var x = newMyType()`. It also ties in fairly well with how `$` is just a procedure which exists just as a procedure which takes a type and returns a string. Similarly these procedures would feel much more like the same concept applied to different types. For macros and generics the benefit is pretty obvious, being able to have the type separate from the function name makes everything easier to compose. A generic procedure for example could support reading any kind of data from a stream with a simple `someObject.genericField = myStream.read(T)` (for reading data into `SomeObject[T] = object; genericField: T`).
