### ISSUE TITLE
Roadmap for Nim

### ISSUE THREAD

**Issue by Araq** [nim-lang/RFCs#437]
>  "The Cylons Were Created by Man. They Rebelled. They Evolved. They Look and Feel Human.
  Some are programmed to think they are Human. There are many copies. **And they have a Plan.**"

It seems to come up regularly that people don't know where Nim is heading, where our focus of development is and what's the PLAN. I'm sorry for not communicating it well but the plan is solid, doesn't change much and it "only" takes longer than I hoped it would take.

# Incremental compilation (IC) / nimsuggest / IDE tooling

This is a single point as for me it's a single thing. If we had a compiler that only recompiles the module that was touched the "nimsuggest" tool can be a simple command line tool that answers a single question like "where is symbol X used?".

The good news is that we have this tool already, it's `nim check --navigate`, the bad news is that its progress is tied to PR https://github.com/nim-lang/Nim/pull/17814. Which is in the state "on hold" until version 1.6.2 is out.

IC is the most important thing for me personally. It's not scheduled for any particular release as it's not about the language nor about its library. Ideally IC will stabilize and be backported to the 1.6.x line.

**Update**: Good IC relies on refactorings of the compilation pipeline. We want to finish these refactorings, release version 2.0 and then finish IC in version 2.x.

# Version 1.6.2

- [x] We will release 1.6.2 near-term (ideally still in 2021) which is 1.6.0 with many bugs ironed out. It is expected that the 1.6.x line is a LTS version, much like 1.2.x is.

# Version 2.0

## Hard goals

For version 2.0 we will make `--gc:orc`, `mimalloc` and `--threads:on` the new defaults.

- [x] `--gc:orc` https://github.com/nim-lang/Nim/pull/20467 https://github.com/nim-lang/Nim/pull/19972
- [x] `--threads:on` https://github.com/nim-lang/Nim/pull/19368
- [x] some way to make the allocator faster for shared memory. One option is `mimalloc` https://github.com/nim-lang/Nim/pull/20359
- [ ] Refactorings of the compilation pipeline in anticipation of IC.

Furthermore, we consider the following experimental features to be stable enough for version 2.0:

- [x] `--experimental:strictEffects` https://github.com/nim-lang/Nim/pull/19380
- [x] `--experimental:unicodeOperators` https://github.com/nim-lang/Nim/pull/20444
- [x] `--experimental:overloadableEnums` https://github.com/nim-lang/Nim/pull/20298
- [x] `-d:nimPreviewFloatRoundtrip` https://github.com/nim-lang/Nim/pull/20195
<del> `-d:nimPreviewDotLikeOps` https://github.com/nim-lang/Nim/pull/19598 </del>

### Language

- [x] Enforce "Definite assignment analysis" for all types, this is easy to do, removes an error-prone aspect of the language, makes the language more consistent and mitigates the problem with `nil` pointers. https://github.com/nim-lang/RFCs/issues/378. https://github.com/nim-lang/Nim/pull/20506

- [x] Deprecate 'unsafeAddr' and make 'addr' available for all addressable locations, see https://github.com/nim-lang/RFCs/issues/369 https://github.com/nim-lang/Nim/pull/19373

- [x] Support `field = defaultValue` inside object declarations. https://github.com/nim-lang/RFCs/issues/252
https://github.com/nim-lang/Nim/pull/20480

### Cleanup of experimental language features

- [ ] "Void type" -- We should optimize away the "empty tuple" type in the backend and remove this feature.
- [x] "Automatic dereferencing" -- We should remove the feature, IMO. It's not a problem worth solving. https://github.com/nim-lang/Nim/pull/20531
- [ ] "AST based overloading" -- Should be removed.
- [ ] "Parallel & Spawn" -- Should be removed. Better done by external packages.
- [x] "Guards and Locks" -- Remove lock levels. https://github.com/nim-lang/Nim/pull/20539

### Stable experimental language features

These features are stable and should be part of the manual.

- [x] "Named argument overloading". https://github.com/nim-lang/Nim/pull/19173
- [x] "Do notation". https://github.com/nim-lang/Nim/pull/19173
- [x] "Type bound operations". https://github.com/nim-lang/Nim/pull/19389
- [x] "Case statement macros". https://github.com/nim-lang/Nim/pull/19173
- [x] "Guards and Locks" -- Move "guards" to the stable documentation. https://github.com/nim-lang/Nim/pull/19173
- [x] "Noalias annotation" -- Stable. https://github.com/nim-lang/Nim/pull/19173

### Library

1. Clean up the system module, move these submodules into their own modules:
   - [x] IO https://github.com/nim-lang/Nim/pull/19442
   - [x] assertion handling https://github.com/nim-lang/Nim/pull/19599
   - [x] thread handling https://github.com/nim-lang/Nim/pull/20711

2. Clean up the OS module, make it more type safe, split it in up in e.g.:
   - [x] path handling (paths.nim) https://github.com/nim-lang/Nim/pull/20582
   - [x] directory handling (dirs.nim): creation, removal, iteration, existence checking https://github.com/nim-lang/Nim/pull/20582
   - [x] file handling (files.nim): creation, removal, existence checking https://github.com/nim-lang/Nim/pull/20582
   - [x] environment variables handling (envvars.nim) https://github.com/nim-lang/Nim/pull/19421
   - [x] symlinks handling (symlinks.nim) https://github.com/nim-lang/Nim/pull/20582
   - [x] OS error reporting (oserrors.nim) https://github.com/nim-lang/Nim/pull/19390

3. The JSON module is also in a poor shape, the API exposes public fields, sometimes is not intuitive (the `%*` operator) and has poor performance. It could be split up into:
   - [-] jsonbuilder
   - [-] jsonparser
   - [-] jsonlexer
   - [-] jsontree
   - [-] jsonmapper: it maps Nim types (objects) to Json types

3. More of the standard library should be moved to external Nimble packages. How
far we get with this is unclear.

### Misc (in comments)

- [x] register callback for marshal in VM https://github.com/nim-lang/Nim/pull/19578; ref https://github.com/nim-lang/RFCs/issues/437#issuecomment-1015878460

# Version 2.x

Every stretch goal of 2.0 that didn't make it into version 2.0, should be
considered a goal for version 2.x.

## Hard goals

We should remove the requirement for forward declarations and allow for recursive module dependencies. Then we can remove these experimental features:

1. "Package level objects"
2. "code reordering"

see also https://github.com/nim-lang/Nim/pull/18818

## Stretch goals

1. Find a better design for "Term rewriting macros". Once done, deprecate the old feature.
2. Find a better design for "Special Operators". Once done, deprecate the old feature.
4. Implement "Aliasing restrictions in parameter passing". The compiler can always produce warnings first.
5. "Strict funcs" / "view types" should be made stable for Nim 2.x.
6. Concepts: Find a way of how to infer `static` values and stabilize the feature.
7. Find a way of allowing a syntax like `of Value(let x, var y)` and embrace an official pattern matching solution that makes use of this syntax.

# Nimble

We hope to be able to ship a new Nimble with the 2.0 release but we are happy to ship it whenever it's ready. See https://github.com/nim-lang/RFCs/issues/398 for good ideas of how to further evolve Nimble. The most important missing feature of Nimble is "lock files" -- Nimble implements it, but not in a way that is compatible with the 1.6.0 Nim compiler.

## How can you help?

The standard library cleanups should be rather easy to do.

**Comment by Vindaar** [comment]
> "AST based overloading" -- Should be removed.

Not sure how I feel about this. Would this also imply removal of the same feature for NimNodes? I rather like that (i.e. specifying a CT proc is only for idents).

To be fair I didn't know this could be used with runtime procedures.

**Comment by hlaaftana** [comment]
> Find a way of allowing a syntax like of Value(let x, var y) and embrace an official pattern matching solution that makes use of this syntax.

Reminds me, default values for object fields was quite popular, is this planned as well? Also the vast number of possible improvements for object variants. I don't know if more improvements to object construction syntax are needed, if there was going to be a `=init` I'm guessing it'll probably be more coherent for it to be similar to `=destroy` instead of a complete override of initialization.

**Comment by Araq** [comment]
> Would json/builder, json/lexer be better

Yes, most people would like that better but I don't want to implement and support `package.module.name` just for a refactoring so I'd go with the name prefixes.

**Comment by konsumlamm** [comment]
> "Void type" -- We should optimize away the "empty tuple" type in the backend and remove this feature.

So eventually, `void` would be replaced by the empty tuple, so that e.g. `proc test() = discard` would return `()` (like it is the case in Rust)?

**Comment by Araq** [comment]
> So eventually, void would be replaced by the empty tuple, so that e.g. proc test() = discard would return () (like it is the case in Rust)?

No, for the return type and discard-checking there would still be a `void`.

**Comment by levovix0** [comment]
+1 for `moduleGroup/module` instead of `moduleGroupmodule`
> I don't want to implement and support package.module.name

why implementing and supporting package.module.name needed for package/module/name?

**Comment by Araq** [comment]
Update: Expanded the section on Nimble.

**Comment by juancarlospaco** [comment]
> "Parallel & Spawn" -- Should be removed. Better done by external packages.

But stdlib keeps `std/tasks` ?, 
I think a way to run multiple stuff at the same time in stdlib is useful !,
at least with a basic API, maybe think of removing Parallel and keep Spawn?

**Comment by Araq** [comment]
`std/tasks` is a "building block", so it should stay.

**Comment by Varriount** [comment]
> +1 for `moduleGroup/module` instead of `moduleGroupmodule`
> 
> > I don't want to implement and support package.module.name
> 
> why implementing and supporting package.module.name needed for package/module/name?

I believe  that this is because `import` only considers the last path component as the module name. The code `from json/lexer import nil` allows accessing all exported routines/types in "./json/lexer.nim" through the `lexer` symbol, not the expression `json.lexer`.

If an expression like `json.lexer` won't be supported, then the symbol "jsonLexer" may be preferable to "lexer", since "jsonLexer" is less ambiguous.

In any case, I don't believe the intention is to remove imports with multiple

**Comment by Araq** [comment]
**Update**: 

- Nimble supports lockfiles and Nim supports the new Nimble.
- Nim version 1.6.2 has been released.

**Comment by juancarlospaco** [comment]
Would be nice to give the jsgen some love too!, at least improve jsgen a little,
the JS stdlib improved a lot and wont produce Showstopper complex bugs,
and the few JS bugs are actually jsgen related bugs actually so ... 🤔

**Comment by a-mr** [comment]
What is policy for breaking changes in 2.0?

I see 2 extreme options:

1. almost no breaking allowed as it is currently in Nim 1.x. The transition to `gc:orc` is an exception.
2. any breaking changes are potentially allowed if it is the right thing. Why would you call it version 2.0 otherwise...

Some concrete examples I know:
* slices are treated differently for different procs `[]`, `[]=`, `delete` and different types (e.g. https://github.com/nim-lang/Nim/issues/16492). It would be great to unify it, but it's a significant breaking change of course.
* `os.walkDir` silently ignores errors (see e.g. https://github.com/nim-lang/Nim/issues/10309 and references). It would be desirable to raise exception by default but we observed that it would break even some code inside Nim repo.
* anchors generated by `docgen` don't preserve information about e.g. `var` in parameter or type of optional parameter with default value (https://github.com/nim-lang/Nim/issues/12373). Fixing that would break previously made references to such anchors.

**Comment by Araq** [comment]
We should fix as much as reasonable, but we need to have a good upgrade path. The worst thing continues to be subtle changes in runtime behavior. That means:

* I don't know what to do with slices.
* Simply deprecate `walkDir` and introduce something that makes sense. Can also be in a module of its own.
* Anchors for v2 are not worth preserving, details like that are not worth

**Comment by zedeus** [comment]
Very cool, nice roadmap. What's the current status, what is the primary project being worked on?

> The good news is that we have this tool already, it's nim check --navigate, the bad news is that its progress is tied to PR nim-lang/Nim#17814. Which is in the state "on hold" until version 1.6.2 is out.

1.6.2 is now out, but there hasn't been any updates to that PR. What's the status of it?

**Comment by Araq** [comment]
> 1.6.2 is now out, but there hasn't been any updates to that PR. What's the status of it?

I never know how to update these RFCs. 1.6.2 is out, next week work on 2.0 will begin.

**Comment by ki0sh1** [comment]
I have to say I do like the plan for 2.0, but I hoped to see something about concurrency too (CSP / Actor?) that would provide low-level and high-level abstractions and being as easy as in Go or Elixir for example, despite the situation has "improved" about multi-threading in general, it should/could be a feature to be included in this plane (in my humble opinion), any news on this matter?

**Comment by ki0sh1** [comment]
I have to say I do like the plan for 2.0, but I hoped to see something about concurrency too (CSP / Actor?) that would provide low-level and high-level abstractions and being as easy as in Go or Elixir for example, despite the situation has "improved" about multi-threading in general, it should/could be a feature to be included in this plan (in my humble opinion), any news on this matter?

**Comment by Araq** [comment]
There is [nim-lang/threading](https://github.com/nim-lang/threading) which is official plus a couple of external packages that do it better than we could hope to. There are currently no plans to bring this into the stdlib for these reasons: 

- We lack the resources; our job shifted to compiler and tooling work which is demanding enough already.
- The stdlib should be trimmed down a bit, not expanded further.
- Most importantly: As separate packages they can evolve much more quickly, not hindered by a deprecation cycle that spans a decade. And not tied to our slow release cycle.

We merely offer the building blocks with destructors, atomics and `std/tasks`.

**Comment by ki0sh1** [comment]
So not being included in the current plan, doesn't necessarily means that it will not be introduced in future, is that correct? I really like Nim for its syntax and features in general, but I would like to know more about what to expect after 2.0 will be out, in particular on the "concurrency story", thank you for your answers.

**Comment by hlaaftana** [comment]
Note for the checklist: guards & locks are in both experimental features to clean up and stable experimental features. Since guards were moved to the stable documentation, it can be marked under the stable experimental features section.

Some RFCs covered by the items:

* #67
* #361

A few simple non-breaking features that could be done at any time, but would be nice to have soon, probably also under 1.6 line:

* #164
* #181
* #220

There are also tons of RFCs related to default object fields and pattern matching but they tend to be larger in scope and discuss other things.

I think "optimize away empty tuple" will take a while compared to the steps for removing the other experimental features. But since it's not tied to a super well known experimental feature it should be fine if it's not 2.0.

Does the `var` in `of Value(let x, var y)` mean `var y: T` or `y: var T`? I don't think it should be the first one given for loops and proc parameters presumably don't have it for a reason. Second one is something the language could do that macros couldn't.

> "Not nil annotation" -- Should be planned for Nim 2.x but removed from the "experimental" manual.

Don't understand this. Is it supposed to be kept in as experimental but undocumented?

**Comment by beef331** [comment]
I just got reminded, is there any chance `marshal` will get removed from the stdlib for 2.0, or at least removing the VM support for it. Almost every json library made can be used at compile time without hard coded VM support, and as most know marshal is just a json serializer.  https://github.com/nim-lang/Nim/blob/devel/compiler/vmgen.nim#L2057-L2065 can cause 10% slower compilation in compile time heavy code(macros included). Since every single call is done with a string search to see if it's from marshal.

**Comment by xflywind** [comment]
Alternative way is to support vmmarshal properly with callback if it is worth.

**Comment by Araq** [comment]
@beef331 wow... that should be fixed indeed.

**Comment by xflywind** [comment]
A simple POC using callback mechanism: https://gist.github.com/xflywind/551d84567cb39d95d0ddcd71f8279e6a

**Comment by xflywind** [comment]
Path related RFCs：

https://github.com/nim-lang/RFCs/issues/54
https://github.com/nim-lang/RFCs/issues/121
https://github.com/nim-lang/RFCs/issues/71

**Comment by Menduist** [comment]
Could we consider https://github.com/nim-lang/RFCs/issues/89 for nim V2?

A few options have been considered, eg the linked RFC, or deprecating naked `except`s, all of them being better than the current status quo, imo

**Comment by Araq** [comment]
Version 2 or not, the guiding principle remains "no secret change in semantics" so we are deprecating `except:`. We could make it not compile altogether for version 2 though.

**Comment by juancarlospaco** [comment]
In Python, naked `except` is allowed, but most linters, IDEs, and tools will complain about it.

**Comment by pyautogui** [comment]
Any plans for nre/re? Removal of one or the other? Cleanup, speedup? (see https://forum.nim-lang.org/t/6008)

**Comment by Araq** [comment]
They should both be moved out of the stdlib, IMO.

**Comment by metagn** [comment]
Some tidbits from the forum thread mentioned up to this point ( https://forum.nim-lang.org/t/9132 ):

* Not breaking, but a lot of support for circular imports/recursive dependencies, so stuff like #416 could be important
* Make overloadable enums non-experimental
* A lot of issues with current object constructor syntax, suggestions varied between `init/new(typedesc)`, `()` for types, changing `:` to `=` for object constructor fields.
* Remove `let a, b = 1` syntax

Also a lot of discussion about stdlib organization and tooling/error messages, but these already seem to be a focus. Other non-breaking but commonly discussed stuff include `sugar` as default import with more macros, and more concept use in stadnard library.

**Comment by xflywind** [comment]
Suggestions for Nim v2 (thanks to @j-james)

ref https://forum.nim-lang.org/t/9132

https://gist.github.com/j-james/08cd36b7475d461d6291416381ce98ad

**Comment by arnetheduck** [comment]
Whatever else happens, adding *more* things, specially more things that don't exist yet (such as random nice-to-haves from v2 forum threads) to 2.0 is a good way to never ship a good 2.0 - shipping orc/arc is already a massive undertaking: it fundamentally changes the way libraries / Nim code should be written (because they now need to think different about memory management, destructor ordering, performance profile, a fresh set of compiler bug workarounds etc etc).

Even enabling ORC/ARC for a simple, small codebase like the compiler itself has proven to be a major difficulty when trying to retain it's previous performance characteristics (or even keep it working without hitting bugs) - to get it across the finish line, the learnings from that ordeal need to be carried back to the standard library itself, which, as such, needs _significant_ work if it is to not be terrible under the new memory regime, let alone to take advantage of the significant improvements and play well with them. 

If anything, a line in the sand around further addtions and 100% focus on `system.nim` to make that the best system possible in a post-2.0-language world would be key targets to look at, such that there emerges a small and stable core / foundation upon which further work can be done.

**Comment by juancarlospaco** [comment]
I would like to re-consider ideas proposed before this Nim 2.0 trend, like:

- Pattern Matching (Requested in many places multiple times).
- https://github.com/nim-lang/Nim/issues/14696
- https://github.com/nim-lang/RFCs/issues/242

**Comment by beef331** [comment]
Slightly related to arne's point. In my quest to make code more reusable I did attempt to make parseutils use `openarray[char]` but it's showed a few issues with openarray/string/cstring that will need to get resolved. Presently due to implicit conversion from string to cstring the following does not work.
```nim
proc doThing(oa: openarray[char]) = discard
proc doThing(str: cstring) = discard
doThing("hello")
```
Similarly the following perhaps should work. Where `openArray[char]` is considered equivalent to `string` in the case of converters.
```nim
type NotString = distinct string
converter toString(s: NotString): string = string(s)
proc doThing(oa: openarray[char]) = discard
doThing(NotString("hello"))
```

**Comment by juancarlospaco** [comment]
The Nim 2.0 can also be a good opportunity to make a decision about Nimble packages clean out,
packages that do not exist anymore and give 404 errors, but they are still in the packages list,
theres multiple issues open and closed in the repo about the problem,
and removing the packages from the JSON looks like it is not allowed (?), 
but it is useless because the repo do not exist anymore,
and sometimes the user also do not exist anymore or is not coding anymore since years ago.

- https://github.com/nim-lang/packages/issues/2075
- https://github.com/nim-lang/packages/issues/1438
- https://github.com/nim-lang/packages/issues/1807
- https://github.com/nim-lang/packages/issues/360
- Probaly more I am missing...

**Comment by CyberTailor** [comment]
> "Parallel & Spawn" -- Should be removed. Better done by external packages

What about bootstrapping build systems/package managers that use threads? Will they need to supply their own implementation of threadpool?

**Comment by Araq** [comment]
No, package managers and bulid systems can use Nimble packages as dependencies if they do the "git clone" commands directly in the build script and/or can use git submodules. A package manager is not like a compiler, it doesn't have to "bootstrap" itself.

**Comment by CyberTailor** [comment]
This is not possible in network-sandboxed environments, and support for
them matters.

**Comment by Araq** [comment]
The sandbox would prevent `nimble install nimble` just as it would prevent `git clone depsThatNimbleRequires`.

**Comment by CyberTailor** [comment]
I've successfully packaged lots of Nim libraries and programs for
Gentoo, which package manager is network-sandboxed (this is the standard
in *nix packaging). Neither git nor nimble are needed for it.

Seems like this discussion is off-topic and should be over.

**Comment by Araq** [comment]
Fine with me, you started the subdiscussion.

**Comment by tomasky** [comment]
I like nim, but cross-compiling is inconvenient. I wish I could cross-compile directly like Golang or ziglang, which would attract more users

**Comment by Araq** [comment]
Just use a CI, cross-compilation won't let you run any tests anyway... I wish we would attract more users who understand software development.

**Comment by Araq** [comment]
Postponed: 
- [ ] Implement https://github.com/nim-lang/RFCs/issues/380, most probably by yet another opt-in switch like `--experimental:typeBoundProcs`. https://github.com/nim-lang/Nim/pull/20520

**Comment by Araq** [comment]
Postponed:

- [ ] The JSON module is also in a poor shape, the API exposes public fields, sometimes is not intuitive (the %* operator) and has poor performance.

**Comment by Araq** [comment]
I'm closing this since version 2.0 is effectively done, we'll only fix even more ORC bugs and release 2.0 in early 2023. The plan for 2023 will be published as an RFC here in the next couple of days.

**Comment by ShalokShalom** [comment]
> I like nim, but cross-compiling is inconvenient. I wish I could cross-compile directly like Golang or ziglang, which would attract more users

https://github.com/enthus1ast/zigcc

Just use the Zig compiler 😉
