### ISSUE TITLE
The Roadmap 2023 for community building

### ISSUE THREAD

**Issue by ringabout** [nim-lang/RFCs#513]
## Projects

- [ ] Maintain a list which contains contribution-friendly issues. Ideally, we should detail solutions of the issue. => https://github.com/orgs/nim-lang/projects/8 

## Packages

We intend to improve the workflow of [packages](https://github.com/nim-lang/packages).

- [ ] Build a better package scanning workflow; implement the new package scanner, which intends to incrementally check newly added packages => https://github.com/nim-lang/packages/pull/2532 drops CI time from 10+ minutes to a few seconds.

- [ ] Post the errors in the form of comments on the PR.

- [ ] Add a cron, which executes a full check for all packages.

## Backporting

- [ ] Improve backporting workflow; adds a backporting bot to automatically backport simple commit. Ideally, it should add a "backporting" label to the specific pull request. If there are some merging conflicts, it needs a manual merging. The pull request with a "backporting" label remaining open is implicitly added to the backporting wishlist. The wishlist can use helps from the community.

## Benchmark

- [ ] Build a benchmark monitoring workflow.

## Specification

- [ ] Build a testable specification workflow => https://github.com/nim-lang/testspec

- [ ] Document all the defines.

## How can you help?

You could join us in [the matrix space](https://matrix.to/#/!ZmWXggMgfkKpcLbQkB:matrix.org?via=matrix.org) where we discuss how to build a community. We appreciate doable suggestions and helps, such as improving the workflow, implementing the roadmap, suggesting doable tasks, reviewing code from contributors. United we stand. We shall work together to make the community thrive.

**The roadmap is subject to changes.**

**Comment by haxscramper** [comment]
```diff
+ - [ ] Remove old, deprecated, unavailable packages (like ones that give 404)
```

https://github.com/nim-lang/packages/pull/1269
https://github.com/nim-lang/packages/issues/2075
https://github.com/nim-lang/packages/issues/1807

**Comment by ringabout** [comment]
@haxscramper Nice catch! Added it to the list.

**Comment by Yepoleb** [comment]
I have tagged all unavailable packages with "deleted". There are some smaller issues still remaining with documentation links but the major problems are resolved.

**Comment by PhilippMDoerner** [comment]
Assuming that the most recent issue doesn't count as part of it in your eyes (https://github.com/pietroppeter/community-management/issues/16), then the setting up of an infrastructure list has been finished, at least in an initial version.

**Comment by esafak** [comment]
Obviously 2023 has come and gone but deleted packages are still taking space in package.json and being served from nimble.directory. Does anyone have a good reason why we shouldn't just nuke them? If not I will prepare the Github workflow to do so.
